---
- name: Respond to Datadog events
  hosts: all
  sources:
    - dd_events:
        app_key: <my_app_key>
        api_key: <my_api_key>
        api_url: 
        interval: 

  rules:
    - name: Catch all Datadog events
      condition: event.id is defined
      action:
        debug: