---
- name: Respond to Datadog events
  hosts: all
  sources:
    - cloin.datadog.dd_events:
        app_key: <my_app_key>
        api_key: <my_api_key>
        api_url: 
        interval: 10

  rules:
    - name: Catch Incidents events
      condition: event.source == "Incidents"
      action:
        debug:

    - name: TRIGGERED toxicstack monitor alerts
      condition: event.source == "Monitor Alert" and event.title is search("toxicstack is responding slowly",ignorecase=true) and event.title is search("Triggered",ignorecase=true)
      action:
        debug:

    - name: RESOLVED toxicstack monitor alerts
      condition: event.source == "Monitor Alert" and event.title is search("toxicstack is responding slowly",ignorecase=true) and event.title is search("Recovered",ignorecase=true)
      action:
        debug:

    - name: Catch Monitor Alert events
      condition: event.source == "Monitor Alert"
      action:
        debug:
    
    - name: Catch all other events
      condition: event.id is defined
      action:
        debug:
